@isTest
public with sharing class DragonTest {

  @isTest
  public static void shouldHaveName() {
    // Dragon dragon1 = new Dragon('Jeff');
    // Assert.areEqual(dragon1.name, 'Jeff');
    // Dragon dragon2 = new Dragon('Louisa');
    // Assert.areEqual(dragon2.name, 'Louisa');
  }

  @isTest
  public static void shouldHaveARider() {
    // Dragon dragon = new Dragon('Saphira', 'Eragon');
    // Assert.areEqual(dragon.name, 'Saphira');
    // Assert.areEqual(dragon.rider, 'Eragon');
  }

  @isTest
  public static void shouldHaveAColor() {
    // Dragon dragon = new Dragon('Saphira', 'Eragon', 'blue');
    // Assert.areEqual(dragon.color, 'blue');
  }

  @isTest
  public static void shouldStartOffBeingHungry() {
    // Dragon dragon = new Dragon('Josh');
    // Assert.areEqual(dragon.hungry, true);
  }

  @isTest
  public static void shouldBeFullAfterEating3Times() {
    // Dragon dragon = new Dragon('Lady Vox');

    // Assert.areEqual(dragon.hungry, true);
    // dragon.eat();
    // Assert.areEqual(dragon.hungry, true);
    // dragon.eat();
    // Assert.areEqual(dragon.hungry, true);

    // dragon.eat();
    // Assert.areEqual(dragon.hungry, false);
  }
}